# Getting started

## Kaggle Notebook Link :

To use numpy, you'll typically start with the following line of code.

In [1]:
import numpy as np

# Creating Arrays from Python Lists

Now we can use `np.array` to create arrays from Python lists:

In [3]:
np.array([1, 4, 3, 5, 6])

array([1, 4, 3, 5, 6])

Remember that unlike Python lists, NumPy arrays can only contain data of the same type. If the types do not match, NumPy will upcast them according to its type promotion rules; here, integers are upcast to floating point:

In [4]:
np.array([2.17, 5, 3, 9, 8])

array([2.17, 5.  , 3.  , 9.  , 8.  ])

In [5]:
np.array([2.17, 5, 3, 9, '23'])

array(['2.17', '5', '3', '9', '23'], dtype='<U32')

If we want to explicitly set the data type of the resulting array, we can use `dtype` keyword:

In [6]:
np.array([2.17, 5, 3, 9, '23'], dtype=np.float64)

array([ 2.17,  5.  ,  3.  ,  9.  , 23.  ])

In [7]:
np.array([2.17, 5, 3, 9, '23'], dtype=np.int64)

array([ 2,  5,  3,  9, 23])

Finally, unlike Python lists, which are always one-dimensional sequences, NumPy arrays can be multidimensional. Here's one way of initializing a multidimensional array using a list of lists:

In [8]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

The inner lists are treated as rows of the resulting two-dimensional array.

# Creating Arrays from Scratch

Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy. Here are several examples: